site_name: Ingenieria de Software 2

#theme: readthedocs

nav:
  - Generalidades:
    - 'Presentación' : 'index.md'
    - 'Antes de empezar': 'antesEmpezar.md'
    - 'Componentes del área de proceso': 'componentesAreaProceso.md'
    - 'Componentes asociados a la seccion CMMI': 'componentesSeccionCMMI.md'
    - 'Componentes informativos de soporte': 'componentesInformativosSoporte.md'
  - CMMI: 'cmmi.md'
  - Presentaciones:
    - 'Christhofer Gutierrez': 'presentaciones/presentacionChristhofer.md'
    - 'Jose Andres' : 'presentaciones/presentacionJoseAndres.md'
    - 'Emily Sinclair' : 'presentaciones/presentacionEmilySinclair.md'
  - Documentos: 'documentos.md'
  - Formatos:
    - 'Seguimiento de Informe Semestral del POI Docente': 'formatoSeguimiento.md'
    - 'Calendario de Asignatura': 'formatoAsignatura.md'
    - 'Clase Dia 1': 'formatoClaseDia1.md'
    - 'Guia de laboratorio': 'formatoGuiaLab.md'
    - 'Avance Programatico Mensual': 'formatoAvanceMensual.md'
    - 'Horas de consulta': 'formatoHoraConsulta.md'
    - 'Informe cualitativo y cuantitativo': 'formatoCualitativo.md'

